version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-aligner
    ports:
      - "8000:8000"
 #   depends_on:
 #     - db
 #   environment:
 #     - DATABASE_URL=postgresql://user:password@db:5432/aligner
 #   volumes:
 #     - .:/app
    restart: always

#  db:
#    image: postgres:15
#    container_name: fastapi-aligner-db
#    restart: always
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: aligner
#    volumes:
#      - pgdata:/var/lib/postgresql/data

#volumes:
#  pgdata:
